# Generated by Django 5.1.1 on 2024-10-06 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booksave',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='book.category'),
        ),
        migrations.AddField(
            model_name='collection',
            name='books',
            field=models.ManyToManyField(to='book.book'),
        ),
        migrations.AddField(
            model_name='goal',
            name='categories',
            field=models.ManyToManyField(to='book.category'),
        ),
        migrations.AddField(
            model_name='story',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='book.book'),
        ),
        migrations.AddField(
            model_name='story',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='book.category'),
        ),
        migrations.AddField(
            model_name='storyuser',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.story'),
        ),
        migrations.AddField(
            model_name='storyuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userbookrating',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='book.book'),
        ),
        migrations.AddField(
            model_name='userbookrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userstatistics',
            name='categories',
            field=models.ManyToManyField(to='book.category'),
        ),
        migrations.AddField(
            model_name='userstatistics',
            name='goals',
            field=models.ManyToManyField(to='book.goal'),
        ),
        migrations.AddField(
            model_name='userstatistics',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
