# Generated by Django 5.1.1 on 2024-10-06 23:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyuser',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 7, 23, 57, 24, 485978, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
