# Generated by Django 5.1.1 on 2024-10-06 23:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_storyuser_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyuser',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 7, 23, 58, 38, 847579, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
