# Generated by Django 5.1.1 on 2024-10-07 01:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_storyuser_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyuser',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 8, 1, 32, 0, 820080, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
