# Generated by Django 5.1.1 on 2024-10-07 08:56

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_storyuser_end_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyuser',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 8, 8, 56, 20, 826290, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.CreateModel(
            name='StorySaveUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Model id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
