# Generated by Django 5.1.1 on 2024-10-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_alter_storyuser_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyuser',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
